name: 'Service Catalog: Sends Payload'
description: 'Sends the result of a health check back to the catalog'
inputs:
  payload_file:
    description: 'The filename of the payload'
    required: false
    default: '/tmp/service-catalog-payload.json'
  result_file:
    description: 'The filename of the result'
    required: false
    default: '/tmp/service-catalog-result.json'
  result:
    description: 'The result of the health check'
    required: false
  message:
    description: 'A message with more detail on the health check'
    required: false
runs:
  using: 'node16'
  main: 'result.js'
branding:
  icon: 'cloud-snow'
  color: 'orange'